/**
 * APP路由转换小程序路由映射文件
 * 从原生小程序完整迁移
 */
import pathMap from './pathMap'

type RouteMapObject = Record<string, string>

const routeMap: RouteMapObject = {
  'nayuki://pindao.cn/home/home': pathMap.home,
  'nayuki://pindao.cn/shopMenu/shopMenu': pathMap.menu,
  'nayuki://pindao.cn/couponShelves/couponShelves': pathMap.couponShelves,
  'nayuki://pindao.cn/activeShelves/activeShelves': pathMap.activeShelves,
  'nayuki://pindao.cn/mine/mine': pathMap.mine,
  'nayuki://pindao.cn/order/order': pathMap.orderList,
  'nayuki://pindao.cn/order/orderDetail': pathMap.orderDetail,
  'nayuki://pindao.cn/userCenter/memberCode': pathMap.memberCode,
  'nayuki://pindao.cn/userCenter/couponPage': pathMap.basicsCoupon,
  'nayuki://pindao.cn/userCenter/couponPageNew': pathMap.basicsCouponNew,
  'nayuki://pindao.cn/userCenter/helpCenterPage': pathMap.helpCenter,
  'nayuki://pindao.cn/userCenter/exchangePage': pathMap.exchangeCenter,
  'nayuki://pindao.cn/userCenter/contactListPage': pathMap.addressList,
  'nayuki://pindao.cn/userCenter/memberRecharge': pathMap.memberRecharge,
  'nayuki://pindao.cn/userCenter/moreServicePage': pathMap.moreService,
  'nayuki://pindao.cn/home/vipNewThingsPage': pathMap.memberNews,
  'nayuki://pindao.cn/gift/giftCardListPage': pathMap.cardList,
  'nayuki://pindao.cn/gift/giftCardPurchaseDetailPage': pathMap.cardBuy,
  'nayuki://pindao.cn/gift/purchaseCouponsPage': pathMap.couponPackageList,
  'nayuki://pindao.cn/collectCup/collectCup': pathMap.collectCup,
  'nayuki://pindao.cn/chargeBack/refund': pathMap.createRefund,
  'nayuki://pindao.cn/chargeBack/refundDetail': pathMap.refundDetail,
  'nayuki://pindao.cn/chargeBack/feedBack': pathMap.comment,
  'nayuki://pindao.cn/chargeBack/invoice': pathMap.invoice,
  'nayuki://pindao.cn/receive/receiveCoupon': pathMap.receiveCoupon,
  'nayuki://pindao.cn/userCenter/exchangeCoupon': pathMap.exchangeCoupon,
  'nayuki://pindao.cn/receive/exchangeCoupon': pathMap.receiveExchange,
  'nayuki://pindao.cn/anniversary/anniversary': pathMap.anniversary,
  'nayuki://pindao.cn/invitation/invitation': pathMap.invitation,
  'nayuki://pindao.cn/order/invoice': pathMap.pkgInvoiceIndex,
  'nayuki://pindao.cn/shelves/shelves': pathMap.shelves,
  'nayuki://pindao.cn/logout/logout': pathMap.logout,
  'nayuki://pindao.cn/memberManage/memberManage': pathMap.memberManage,
  'nayuki://pindao.cn/sharesCenter/sharesCenter': pathMap.sharesCenter,
  'nayuki://pindao.cn/giftZone/giftZone': pathMap.giftZone,
  'nayuki://pindao.cn/historicRecords/historicRecords': pathMap.historicRecords,
  'nayuki://pindao.cn/pointsDetail/pointsDetail': pathMap.pointsDetail,
  'nayuki://pindao.cn/studentInvitation/studentInvitation': pathMap.studentInvitation,
  'nayuki://pindao.cn/activeLand/activeLand': pathMap.activeLand,
  'nayuki://pindao.cn/student/student': pathMap.authentication,
  'nayuki://pindao.cn/paradise/paradise': pathMap.paradise,
  'nayuki://pindao.cn/bankOffers/bankOffers': pathMap.bankOffers,
  'nayuki://pindao.cn/eightAnniversary/raffle': pathMap.eightRaffle,
  'nayuki://pindao.cn/eightAnniversary/ballot': pathMap.eightBallot,
  'nayuki://pindao.cn/bankOffers/detail/detail': pathMap.bankActivityDetail,
  'nayuki://pindao.cn/student/coupon/invite': pathMap.studentCouponsInvite,
  'nayuki://pindao.cn/student/coupon/receive': pathMap.studentCouponsReceive,
  'nayuki://pindao.cn/eightAnniversary/answer/answer': pathMap.eightAnniversary,
  'nayuki://pindao.cn/annualReport/index/index': pathMap.annualReportIndex,
  'nayuki://pindao.cn/annualReport/invite/index': pathMap.annualReportInviteIndex,
  'nayuki://pindao.cn/annualReport/raffle': pathMap.annualRaffle,
  'nayuki://pindao.cn/jointly/recharge': pathMap.jointlyRecharge,
  'nayuki://pindao.cn/jointly/areaSelect': pathMap.jointlyAreaSelect,
  'nayuki://pindao.cn/password/exchange': pathMap.pwdExchange,
  'nayuki://pindao.cn/vote/vote': pathMap.vote,
  'nayuki://pindao.cn/cardCollect/cardCollect': pathMap.cardCollect,
  'nayuki://pindao.cn/fission/coupon/receive': pathMap.fissionCouponsReceive,
  'nayuki://pindao.cn/loong/annual/report': pathMap.loongAnnualReportIndex,
  'nayuki://pindao.cn/personalityTest/personalityTest': pathMap.personalityTest,
  'nayuki://pindao.cn/topRanking/topRanking': pathMap.topRanking,
  'nayuki://pindao.cn/consumerDetails/consumerDetails': pathMap.consumerDetails,
  'nayuki://pindao.cn/valentinesDay/valentinesDay': pathMap.valentinesDayReceive,
  'nayuki://pindao.cn/hongbao/index': pathMap.receiveHongbao,
  'nayuki://pindao.cn/equityCard/equityCard': pathMap.equityCard,
  'nayuki://pindao.cn/equityCardDetail/equityCardDetail': pathMap.equityCardDetail,
  'nayuki://pindao.cn/inviteGift/inviteGift': pathMap.inviteGift,
  'nayuki://pindao.cn/legumes/index': pathMap.legumesIndex,
  'nayuki://pindao.cn/invitation/index': pathMap.receiveYinYueHe,
  'nayuki://pindao.cn/medal/medal': pathMap.medal,
  'nayuki://pindao.cn/niceCard/niceCard': pathMap.niceCard,
  'nayuki://pindao.cn/task/detail': pathMap.taskDetail
}

export default routeMap
